# Generated by Django 3.2.10 on 2024-11-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0014_equipos_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes_cartas',
            name='E',
            field=models.TextField(default='NC', max_length=1000000),
        ),
    ]
