# Generated by Django 3.2.10 on 2026-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0017_momios'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes_cartas',
            name='CM',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='imagenes_cartas',
            name='PI',
            field=models.TextField(default='NC', max_length=1000000),
        ),
    ]
