# Generated by Django 3.2.10 on 2026-02-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0018_auto_20260210_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos_fotos',
            name='alemania',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='arabia_saudita',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='argelia',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='argentina',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='australia',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='austria',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='belgica',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='brasil',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='cabo_verde',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='canada',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='colombia',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='corea',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='costa_de_marfil',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='croacia',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='curazao',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='ecuador',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='egipto',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='escocia',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='espania',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='eua',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='francia',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='ghana',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='haiti',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='holanda',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='inglaterra',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='iran',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='japon',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='jordania',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='m1',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='m2',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='m3',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='m4',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='m5',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='m6',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='marruecos',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='mexico',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='noruega',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='nueva_zelanda',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='panama',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='paraguay',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='portugal',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='qatar',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='senegal',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='sudafrica',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='suiza',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='tunez',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='uruguay',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='uzbekistan',
            field=models.TextField(default='NC', max_length=1000000),
        ),
    ]
