# Generated by Django 3.2.10 on 2026-03-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0019_auto_20260227_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificados', models.TextField(default='NC', max_length=1000000)),
            ],
        ),
    ]
