# Generated by Django 3.2.10 on 2026-04-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llenar_quiniela', '0021_auto_20260306_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos_fotos',
            name='boznia',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='congo',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='irak',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='republica_checa',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='suecia',
            field=models.TextField(default='NC', max_length=1000000),
        ),
        migrations.AddField(
            model_name='equipos_fotos',
            name='turquia',
            field=models.TextField(default='NC', max_length=1000000),
        ),
    ]
