# Generated by Django 3.2.10 on 2024-11-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabla_general', '0015_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartas_aux',
            name='j1',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j10',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j11',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j12',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j13',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j14',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j15',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j16',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j17',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j2',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j3',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j4',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j5',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j6',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j7',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j8',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartas_aux',
            name='j9',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
