# Generated by Django 3.2.10 on 2026-01-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('titulos', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Titulos',
                'verbose_name_plural': 'Titulos',
            },
        ),
    ]
