# Generated by Django 3.2.10 on 2026-01-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_titulos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Q1', models.IntegerField(default=0)),
                ('Q2', models.IntegerField(default=0)),
                ('Q3', models.IntegerField(default=0)),
                ('Q4', models.IntegerField(default=0)),
                ('Q5', models.IntegerField(default=0)),
                ('Q6', models.IntegerField(default=0)),
                ('Q7', models.IntegerField(default=0)),
                ('Q8', models.IntegerField(default=0)),
                ('Q9', models.IntegerField(default=0)),
                ('Q10', models.IntegerField(default=0)),
                ('Q11', models.IntegerField(default=0)),
                ('Q12', models.IntegerField(default=0)),
                ('Q13', models.IntegerField(default=0)),
                ('Q14', models.IntegerField(default=0)),
                ('Q15', models.IntegerField(default=0)),
                ('Q16', models.IntegerField(default=0)),
                ('Q17', models.IntegerField(default=0)),
                ('Q18', models.IntegerField(default=0)),
                ('Q19', models.IntegerField(default=0)),
                ('Q20', models.IntegerField(default=0)),
                ('Q21', models.IntegerField(default=0)),
                ('Q22', models.IntegerField(default=0)),
                ('Q23', models.IntegerField(default=0)),
                ('Q24', models.IntegerField(default=0)),
                ('Q25', models.IntegerField(default=0)),
                ('Q26', models.IntegerField(default=0)),
                ('Q27', models.IntegerField(default=0)),
                ('Q28', models.IntegerField(default=0)),
                ('Q29', models.IntegerField(default=0)),
                ('Q30', models.IntegerField(default=0)),
            ],
        ),
    ]
