# Generated by Django 3.2.10 on 2026-01-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_historico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historico',
            options={'verbose_name': 'Historico', 'verbose_name_plural': 'Historicos'},
        ),
        migrations.RenameField(
            model_name='historico',
            old_name='Nombre',
            new_name='nombre',
        ),
    ]
